### ISSUE TITLE
When trying to create cluster with low pri vms getting error

### ISSUE THREAD

**Issue by dciborow** [Azure/aztk#226] opened 2017-11-21 17:46 UTC
Freshly checkout from stable...
```batch
$ aztk spark cluster create --id testCluster2 --size-low-pri 2 --vm-size standard_d2_v2
```

```
Output:
-------------------------------------------
spark cluster id:        testCluster2
spark cluster size:      4
>        dedicated:      2
>     low priority:      2
spark cluster vm size:   standard_d2_v2
custom scripts:          None
docker repo name:        jiata/aztk:0.1.0-spark2.2.0-python3.5.4
wait for cluster:        True
username:                spark
-------------------------------------------
Loaded spark-defaults.conf
Loaded spark-env.sh
Please input a password for user 'spark':
Please confirm your password for user 'spark':
-------------------------------------------
Exception encountered:
Pool cannot have both TargetDedicatedNodes and TargetLowPriorityNodes specified if communication is enabled.
RequestId:8b312c71-1649-4004-86c2-8f1f0334f0af
Time:2017-11-21T17:42:17.8084423Z
-------------------------------------------
```

**Comment by timotheeguerin** [comment] 2017-11-21 17:51
You unfortunately currently cannot use both dedicated and low priority VMs in the same cluster yet.

**Comment by timotheeguerin** [comment] 2017-11-21 20:33
Hhm, I think the problem is that the cluster.yaml contains 2 for the dedicated size and so it tries to use both. Can you check it does and set `size` to 0 in `cluster.yaml`. It is something we should update because as you noticed this can be quite confusing

**Comment by audac1ty** [comment] 2017-11-22 14:05
@timotheeguerin Can confirm that this solution worked for my issue re: low-prio nodes. 

May be easier to amend the default cluster.yaml file so the sizes of both are set to 0 as default and amend the readme to reflect the change?

**Comment by timotheeguerin** [comment] 2017-11-22 15:49
I talked to a teammate and this confusing issue was fixed some time ago but should only be on master not stable yet. You are free to try it out from master. @jafreck can confirm.

**Comment by jafreck** [comment] 2017-12-19 00:54
Closing since stable was updated and this issue has been fixed.

**Closed by jafreck** 2017-12-19 00:54 UTC
